### ISSUE TITLE
Maybe should be a 13 factor?

### ISSUE THREAD

**Issue by IuryAlves** [adamwiggins/12factor#23]
The 12 factor is awesome! It's a thing that i always recommend to all developers that i know. But when i talk about the 12 factor i always talk about infrastructure as code too.

Infrastructure as code is a thing that every developer should keep in mind. So why not add infrastructure as code as a thirteen factor?

**Comment by someoneinatree** [comment]
I get where this is coming from, but also, one of the nice things I've found about 12-factor is that for certain use-cases, e.g. node app deployed on heroku, there is not necessarily any infrastructure code needed.

And that's a good thing to aim for! These are "app" guidelines, which strictly speaking is (or, generally speaking, should ideally be) agnostic to the deployment conditions of that app.

You set up your heroku project, hook up a repo, write a pipeline. That small process itself might be worth putting into code, but as it's a flow that many projects might want to use, it makes sense for it to be separate codebase, rather than as a requirement of any particular app.

**Comment by IuryAlves** [comment]
@someoneinatree  You`re right.
